name: 🐛 バグ報告
description: 不具合を報告する
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        以下の情報を記入してください。

  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 不具合の概要を記載
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順
      description: バグを再現するための手順を記載
      placeholder: |
        1. '...' に移動
        2. '....' をクリック
        3. '....' までスクロール
        4. エラーが発生
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: 期待する動作
      description: 本来期待される動作を記載
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: 発生したブラウザ
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - その他
